---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - manojs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - manojs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - manojs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - rams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - rams/finalizers
  verbs:
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - rams/status
  verbs:
  - get
  - patch
  - update
